# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DoubanLoginModule' do

  pod "CTMediator"
  
  target 'FrameworkDoubanLoginModule' do
      pod "CTMediator"
  end

end
